# Generated by Django 5.1.3 on 2024-11-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('image_file', models.ImageField(blank=True, upload_to='')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
