# Generated by Django 5.1.3 on 2024-11-22 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project', '0003_rename_score_anime_rating_remove_anime_aired_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='rating',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='mal_id',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='source',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='studio',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='type',
        ),
        migrations.AddField(
            model_name='anime',
            name='aired',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='img_url',
            field=models.URLField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='link',
            field=models.URLField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anime',
            name='uid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='genre',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='anime',
            name='popularity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anime',
            name='ranked',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='synopsis',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
