# Generated by Django 5.1.3 on 2024-11-22 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project', '0004_rename_rating_anime_score_remove_anime_mal_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('role', models.CharField(choices=[('main', 'Main'), ('supporting', 'Supporting'), ('antagonist', 'Antagonist')], default='supporting', max_length=50)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('popularity', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='final_project.anime')),
            ],
        ),
    ]
