# Generated by Django 5.1.3 on 2024-11-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project', '0006_user_favorite_anime_merchandise'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='selected_merchandise',
            field=models.ManyToManyField(blank=True, related_name='buyers', to='final_project.merchandise'),
        ),
    ]
