# Generated by Django 5.1.3 on 2024-11-28 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project', '0008_user_auth_user_user_unique_auth_user_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_user',
            field=models.ForeignKey(help_text='The associated Django auth user.', on_delete=django.db.models.deletion.CASCADE, related_name='custom_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
