# Generated by Django 5.1.3 on 2024-12-03 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('final_project', '0011_merchandise_image_url_alter_profile_auth_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchandise',
            name='description',
        ),
    ]
