# Generated by Django 5.1.3 on 2024-12-03 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project', '0013_audiofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='description',
        ),
        migrations.AddField(
            model_name='audiofile',
            name='anime',
            field=models.ForeignKey(blank=True, help_text='The anime associated with this audio file', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='final_project.anime'),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='artist',
            field=models.CharField(default=1, help_text='Artist of the audio file', max_length=255),
            preserve_default=False,
        ),
    ]
