# Generated by Django 5.1.3 on 2024-12-03 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project', '0014_remove_audiofile_description_audiofile_anime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='anime',
            field=models.ForeignKey(default=1, help_text='The anime associated with this audio file', on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='final_project.anime'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the video', max_length=255)),
                ('file', models.FileField(help_text='Upload MP4 file', upload_to='videos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='Date and time the file was uploaded')),
                ('anime', models.ForeignKey(help_text='The anime associated with this video', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='final_project.anime')),
            ],
        ),
    ]
