# Generated by Django 5.1.2 on 2024-11-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='date_of_birth',
            field=models.DateField(help_text="Voter's date of birth"),
        ),
        migrations.AlterField(
            model_name='voter',
            name='date_of_registration',
            field=models.DateField(help_text='Date the voter registered to vote'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='first_name',
            field=models.CharField(help_text="Voter's first name", max_length=50),
        ),
        migrations.AlterField(
            model_name='voter',
            name='last_name',
            field=models.CharField(help_text="Voter's last name", max_length=50),
        ),
        migrations.AlterField(
            model_name='voter',
            name='party_affiliation',
            field=models.CharField(help_text="Voter's party affiliation", max_length=50),
        ),
        migrations.AlterField(
            model_name='voter',
            name='precinct_number',
            field=models.CharField(help_text="Precinct number associated with the voter's address", max_length=10),
        ),
        migrations.AlterField(
            model_name='voter',
            name='residential_apartment_number',
            field=models.CharField(blank=True, help_text='Apartment number, if applicable', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='residential_street_name',
            field=models.CharField(help_text="Street name of the voter's residential address", max_length=100),
        ),
        migrations.AlterField(
            model_name='voter',
            name='residential_street_number',
            field=models.CharField(help_text="Street number of the voter's residential address", max_length=10),
        ),
        migrations.AlterField(
            model_name='voter',
            name='residential_zip_code',
            field=models.CharField(help_text="Zip code of the voter's residential address", max_length=10),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v20state',
            field=models.BooleanField(help_text='Participation in 2020 State Election'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v21primary',
            field=models.BooleanField(help_text='Participation in 2021 Primary Election'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v21town',
            field=models.BooleanField(help_text='Participation in 2021 Town Election'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v22general',
            field=models.BooleanField(help_text='Participation in 2022 General Election'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='v23town',
            field=models.BooleanField(help_text='Participation in 2023 Town Election'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='voter_score',
            field=models.IntegerField(help_text='Number of elections the voter participated in (out of 5)'),
        ),
    ]
